* EFM: An Edge-Computing-Oriented Forwarding Mechanism for Information-Centric Networks
* Edge Cache-based Intelligent Content Delivery in Information-Centric Wireless Networks
* Evaluation of a Geo-region Based Architecture for Information Centric Disruption Tolerant Networks
* On the Effect of Communication Link Heterogeneity on Content Delivery Delay in Information-Centric Delay Tolerant Networks
* Distributed Cooperative Caching for Wireless Information Centric Networks: Local Request Rate Approach
* Emergency Disaster Information Delivery on Information-Centric Networking
* Data Aggregation with multiple sinks in Information-Centric Wireless Sensor Network
* Fast Content Delivery Using a Testbed-Based Information-Centric Network
* A survey on Information-centric Networking: Rationales, designs and debates
* An Energy-Efficient Information-Centric Model for Internet of Things Applications
* ICNRL: An Initiative Framework Towards Information Centric Network Representation
* Testbed-based Performance Evaluation of the Information-Centric Network
* Pseudonym Authentication on Network Layer in Information-Centric Networks
* SGX-ICN: A Secure and Privacy-Preserving Information-Centric Networking with SGX Enclaves
* Information-Centric Wireless Sensor Networking Scheme With Water-Depth-Awareness Content Caching for Underwater IoT
* ICN-OMF: A control, management framework for Information-Centric Network testbed
* Analysis of Content Availability at Network Failure in Information-Centric Networking
* Information-Centric Networking Cache Robustness Strategy for System Wide Information Management
* Software Defined Networking based Information Centric Networking: An Overview of Approaches and Challenges
* A Secured Dialog Protocol Scheme Over Content Centric Networks
* Distributed Fog-based Caching Solution for Content-Centric Networking in IoT
* Peer-Assisted Information-Centric Network (PICN): A Backward Compatible Solution
* Fast eHealth Information Delivery in the ICN-based Mobile Networks
* Information-Centric Networks: Categorizations, challenges, and classifications
* Enhancing Information Resilience in Disruptive Information-Centric Networks
* An Information-centric NFV-based System Implementation for Disaster Management Services
* A Cluster-based Mechanism for Vehicular Networks in the Scale-Free ICN Core Network
* Topology-based data dissemination approaches for large scale data centric networking architecture
* Propose of the dynamic route switching method in Information-Centric Networking-based wireless sensor network
* An information-centric multiple-source routing scheme for wireless sensor networks
* Age of Information Modeling and Optimization for Fast Information Dissemination in Vehicular Social Networks
* Application of Fault Management to Information-Centric Networking
* E-health application using network coding based caching for Information-centric networking (ICN)
* Content-Centric Community-Aware Mobile Social Network Routing Scheme
* An Efficient Congestion Control Model utilizing IoT wireless sensors in Information-Centric Networks
* Performance-based congestion control in information centric network
* Time Based Concave Cache Pricing for Information-centric Networks
* A state-of-the-art environment for research, design, evaluation, prototyping, and integration of dual-use advanced networking and network-centric information technologies
* A network virtualization framework for information centric data center networks
* Review on Network Function Virtualization in Information-Centric Networking
* LAC: Introducing latency-aware caching in Information-Centric Networks
* Improving network performance of healthcare services using Content-Centric Network model
* Hete_MESE: Multi-Dimensional Community Detection Algorithm Based on Multiplex Network Extraction and Seed Expansion for Heterogeneous Information Networks
* A Novel Forwarding and Caching Scheme for Information-Centric Software-Defined Networks
* HHR: hierarchical hybrid routing scheme for information-centric network
* X-centric positioning: A combination of device-centric and multi-rat network-centric positioning approaches in NGN
* Challenges of name resolution service for information centric networking toward IoT
* In-Network Data Aggregation for Information-Centric WSNs using Unsupervised Machine Learning Techniques
* Identity-based Secret Sharing Access Control Framework for Information-Centric Networking
* FCSS: Fog-Computing-based Content-Aware Filtering for Security Services in Information-Centric Social Networks
** 9350827
** 8606009
** 8685612
** 9842628
** 8940723
** 8690535
** 6799475
** 9478856
** 7188520
** 9807720
** 8605940
** 9289603
** 9063215
** 9350832
** 9351540
** 7057932
** 9269071
** 9084131
** 9493541
** 9853045
** 9700561
** 8100706
** 9621123
** 6839927
** 8306511
*** Information-Centric Networking (ICN) has attracted much attention as a promising future network design, which presents a paradigm shift from host-centric to content-centric. However, in edge computing scenarios, there is still no specific ICN forwarding mechanism to improve transmission performance. In this paper, we propose an edge-oriented forwarding mechanism...Show More
*** As mobile data traffic increases explosively, content delivery issue in the Internet is a growing concern. In order to fundamentally solve this problem, information-centric networking has recently been proposed and applied to wireless networks. However, the influence of edge caches and related decision schemes on the performance of content delivery is largely ignored in the...Show More
*** Information Centric Disruption Tolerant Networks (ICDTNs) have recently been proposed as a powerful approach to provide effective data and information sharing when existing communication infrastructures are degraded or destroyed. This paper explores using a hybrid approach for ICDTN construction using Named Data Networking (NDN) and DTN architectures that avoids the n...Show More
*** In recent years, it is expected that ICDTN (Information-Centric Delay/Disruption- Tolerant Net-working) incorporating the communication paradigm of Information-Centric Networks will be realized in an environment where communication links between nodes are intermittent, and its effectiveness has been actively investigated. To realize efficient content delivery in ICDTN...Show More
*** In present decade, new technologies emerging very fast which gives the facilities to both service providers and consumers. Smartphones and Tablets armed with abundant of storage capacity, fast processors speed and recent layer-2 technology, which permit the D2D communication that increases the performance of in-network wireless communication. These factors motivates to devise a new paradigm ...Show More
*** Information-Centric Networking (ICN) is attracting attention as a content distribution method against increasing network traffic. On the other hand, emergency information is required to be reliably transmitted even under network traffic congestions. This paper analyses network congestions of ICN. And we propose a new method that a router adds emergency ...Show More
*** Many studies have explored data aggregation in different network architectures. There are two critical methods in data aggregation: Directed Diffusion in flat networks, and Tree-Based Data Aggregation in hierarchical networks. However, each data aggregation method has problems in multiple-sink environments. In Directed Diffusion, even if one sink has already reinforced a high-qua...Show More
*** Key requirements for a better performance of multimedia applications typically include lower latency, improved security, faster content retrieval, and adjustability to the traffic load. However, the current Internet often fails to meet the requirements due to the drawbacks of the host-oriented communication architecture. Those drawbacks can be overcome by a well-recognized networking paradig...Show More
*** The basic function of the Internet is to delivery data (what) to serve the needs of all applications. IP names the attachment points (where) to facilitate ubiquitous interconnectivity as the current way to deliver data. The fundamental mismatch between data delivery and naming attachment points leads to a lot of challenges, e.g., mapping from data name to IP address, handling dynamics of underlyin...Show More
*** The Information-Centric Networking (ICN) is considered a network paradigm for the Internet of Things (IoT) applications. ICN works on data naming conventions and fits perfectly in distributed computing. LoRa has been adopted for long-range, interference-free communication for multiple IoT applications. We demonstrate that LoRa networks' energy consumption can be signi...Show More
*** The exponentially growing demand for computational resources prevents the Information Centric Networking (ICN) being deployed in practice due to the high dimensional sparse data computation. However, we argue that Network Representation Learning (NRL) can help to solve the problem by transforming the raw network information data into low-dimensional dense adjace...Show More
*** Proliferation of the Internet usage is rapidly increasing, and it is necessary to support the performance requirements for multimedia applications, including lower latency, improved security, faster content retrieval, and adjustability to the traffic load. Nevertheless, because the current Internet architecture is a host-oriented one, it often fails to support the necessary demands such as fast co...Show More
*** The current data-centric security architecture for the Information Centric Network (ICN) does not provide efficient user authentication mechanisms, thus causing undesirable issues such as interest flooding attacks (IFA). In order to address them, this paper proposes a pseudonym authentication scheme on network layer based on the system of identity-based cryptography (...Show More
*** As the next-generation network architecture, Information-Centric Networking (ICN) has emerged as a novel paradigm to cope with the increasing demand for content delivery on the Internet. In contrast to the conventional host-centric architectures, ICN focuses on content retrieval based on their name rather than their storage location. However, ICN is vulnerable to vari...Show More
*** The existing Underwater Internet of Things (UIoT) is based on the IP architecture, which is not conducive to the efficient storage and distribution of huge amounts of content generated in underwater. Actively pushing all content to users causes much unnecessary resource consumption in the UIoT. The information-centric networking (ICN) architecture opens new horizons up for these ...Show More
*** A publisher/subscriber model dominates today's Internet usage behavior instead of a location-based host access. Along with this stream, Information-Centric Network (ICN) is proposed for Future Internet Architecture to remedy the problems the current Internet is encountered. Although there are lots of research efforts on ICN, but still evaluation and validation of their proposals ...Show More
*** In recent years, ICN (Information-Centric Networking) has been under the spotlight as a network that mainly focuses on transmitted and received data rather than on the hosts that transmit and receive data. Generally, the communication networks such as ICNs are required to be robust against network failures caused by attacks and disasters. One of the metrics for ...Show More
*** This study focused on the data center overload and resource allocation imbalance problem during the task processing of System Wide Information Management (SWIM). The Information-Centric Networking (ICN) technology was adopted in the infrastructure level of SWIM. In order to guarantee the cache performance of ICN in SWIM, and reduce the impact of cache node failure on the [:...Show More
*** ICN (Information-Centric Networking) is a traditional networking approach which focuses on Internet design, while SDN (Software Defined Networking) is known as a speedy and flexible networking approach. Integrating these two approaches can solve different kinds of traditional networking problems. On the other hand, it may expose new challenges. In this pap...Show More
*** Internet architecture has transformed into a more complex form than it was about a decade back. Today the internet comprises multimedia information where services and web applications have started to shift their focus on content. In our perspective of communication systems, content-centric networking (CCN) proposes a new methodology. The use of cache memory at the network l...Show More
*** The development of micro electronic systems combined with the emergence of new information and communication technologies has allowed the integration of data collection, processing and transmitting functionalities in a single tiny device which is the wireless sensor. As a result, networks composed of these sensors offer a host of advantages over traditional networks, including [:...Show More
*** Information-centric networking (ICN) is a promising solution for most of Internet applications where the content represents the core of the application. However, the proposed solutions for the ICN architecture are associated with many complexities including pervasive caching in the Internet and incompatibility with legacy IP networks, so the deployment of ICN in real net...Show More
*** eHealth information should be delivered within a very short amount of time, in particular, in an emergency situation. eHealth content is delivered from a server upon receiving a request for the content via the network. The location of the content server may be far away from the content requester. In this case, the content delivery time can be large and therefore does not satisfy the co...Show More
*** Information-Centric Networking (ICN) emerges as a promising approach for content dissemination and retrieval with a number of advantages including efficient content delivery, better bandwidth utilization and improved mobility support. In past few years, several ICN architectures have been proposed offering different set of features and characteristics, which makes it difficult to...Show More
*** We argue that data communications in dynamic and potentially fragmented networks should not and cannot rely on network-centric resilience schemes, as is the case in today's networks, but should take advantage of techniques that focus on information-centric resilience. We make the case that management and control in disruptive environments should take advantage o...Show More
*** When disasters occur, they not only affect the human life. Therefore, communication in disaster management is very important. During the disaster recovery phase, the network infrastructure may be partially fragmented and mobile rescue operations may involve many teams with different roles which can dynamically change. Therefore, disaster management services require high flexibility both in t...Show More
*** The repetition of content requests happens frequently in the vehicular networks, and it is increasing depending on the vehicular density in a certain area. On the other hand, information-centric networking (ICN) is being used in the vehicular networks to fulfill the faster content communication requirements, reduce latency, and enhance the network capacity. Alth...Show More
*** Massive information flows are generated from interactive processing and visualizations. To efficiently support information transmission over the Internet, information centric architecture has been recently proposed. In this paper, we consider an information centric architecture, called the data centric networking architecture to provide communication...Show More
*** Many industries expect M2M services which collect a variety of data through sensor networks. However, in general, a sensor network is designed for applying a single service. On the other hand, ICN (Information-Centric Networking) is known as one of new generation networks. Applying ICN for sensor network, the sensor network platform to provide a vari...Show More
*** In wireless sensor networks, Information-Centric Networks (ICN) are used as the next generation network architecture to perform non-TCP/IP communications. Meanwhile, Disruption/Delay Tolerant Networks (DTN) architecture has solved the problem of unable to communicate caused by frequent interruptions, node mobility or lacking of energy by storing the requested da...Show More
*** Autonomous vehicles (AVs) with advanced communication, computing, and control capabilities will provide not only a convenient means of transportation but also an emerging platform for real-time social communications and networking. Thereby, it is crucial to enable timely exchange of information over the dynamic cyber-physical-social system enabled by the AVs. In this paper, we consider...Show More
*** Current approaches to Information-Centric Networking (ICN) facilitate the publication and retrieval of content in a network through a variety of discovery, caching and forwarding approaches, thus defining an equivalent of the data plane in the current Internet infrastructure. However, in contrast to the current Internet, ICN lacks a definition of the control plane for the m...Show More
*** Beginning with the recent availability of wireless medical sensor prototype and growing, the need for E-health care application record databases, we analyze the requirement of a unified communication framework in overcoming generation network. This paper proposes Information-centric networking based framework over WBAN as the primary enabler for E-health applications. If us...Show More
*** MSN (Mobile Social Network) enables nodes (mobile devices) to realize packet delivery by leveraging social relationships of mobile users. However, MSN has to adapt with the daily increasing content (e.g., video) requirement requested by mobile users. Based on the fact that ICN (Information-Centric Networking) supports mobility naturally, we propose an MSN content-centric...Show More
*** Congestion control is one of the essential keys to enhance network efficiency so that the network can perform well even in the case of packet drop. This problem is even more challenging in Information-Centric Networking (ICN), a typical Future Internet design, which employs the packet flooding policy for forwarding the information. To diminish the high traffic l...Show More
*** In the past years, huge data is passing through internet and this demands renovation to the TCP/IP networks. Information centric network is suggested to resolve limitation of address based communication in TCP/IP network. As one of ICN architecture, data transmission in Named Data Network (NDN) is performed by address based content pulling. To pull content, pack...Show More
*** To distribute contents through Information-centric networks (ICN) was proposed as an important future Internet architecture, in which contents was considered as the main part. In ICN, contents name are the routing locator for efficient contents distribution. Contents are dynamically cached in network routers of Internet service providers (ISPs), which is different from trad...Show More
*** There are a large number of major military modernization initiatives in place to employ a digitized, network-centric, information-dominant fighting force in the next century. The evolution of both military and commercial information systems from platform-centric to network-centric architectures necessitates the creation of cross-platform environments for d...Show More
*** In this poster we have proposed a novel network virtualization framework for information centric data center networks that decouples the control plane and data plane, where the fully distributed data plane is controlled and managed by a well-defined and centralized control plane. Exploiting some network virtualization notion, the proposed framework provides an easily ...Show More
*** Network function virtualization (NFV / VNF) and information-centric networking (ICN) are two trending technologies that have attracted expert's attention. NFV is a technique in which network functions (NF) are decoupling from commodity hardware to run on to create virtual communication services. The virtualized class nodes can bring several advantages such as reduce O...Show More
*** Latency-minimization is recognized as one of the pillars of 5G network architecture design. Information-Centric Networking (ICN) appears a promising candidate technology for building an agile communication model that reduces latency through in-network caching. However, no proposal has developed so far latency-aware cache management mechanisms for ICN. In the paper, we...Show More
*** Healthcare and hospital are the most complex service systems because healthcare records are distributed in various locations. The huge of data is used in the hospital for patients' treatment, which consume a lot of communication bandwidth. The dynamics circuit network (DCN) is one of the Future Internet applications that support the dedicated bandwidth network. However, this approach n...Show More
*** Most real-world information networks are heterogeneous, which contain multiple types of entities and relations between the entities. Large-scale and heterogeneity are the typical properties of heterogeneous information networks, and their community structures are often overlapping, complex, and diverse. The existing community detection algorithms without considering the abo...Show More
*** This paper integrates Software-Defined Networking (SDN) and Information -Centric Networking (ICN) framework to enable low latency-based stateful routing and caching management by leveraging a novel forwarding and caching strategy. The framework is implemented in a clean- slate environment that does not rely on the TCP/IP principle. It utilizes Pending Interest Tables (PIT) ...Show More
*** Publish/subscribe (pub/sub) paradigm is the main communication model for Information-Centric Network (ICN) proposals. A key issue for pub/sub system is how to route the content objects to the correct subscribers, and ICN is no exception. ICN network would be divided into core domain and many edge domains as today's internet does. HHR (Hierarchy Hybrid Routing scheme) is pre...Show More
*** Positioning, being one of the main factors shaping services that deliver information to users based on their location, has experienced huge advancements over the past years. Today, the combination of device-centric positioning approaches, such as GPS, and device-assisted approaches, such as Cell-Id and WiFi positioning technologies, has proved to be very popular among mobile platforms....Show More
*** Information-Centric Networking (ICN) has been recognized as a promising technology for the future Internet architecture. The primary communication object in ICN is the named data object (NDO) and its main goal is the efficient dissemination and retrieval of the NDOs in a global scale. In this regard, ICN can be a candidate architecture in IoT environment since IoT focuses on data...Show More
*** IoT applications are changing our daily lives. These innovative applications are supported by new communication technologies and protocols. Particularly, the information-centric network (ICN) paradigm is well suited for many IoT application scenarios that involve large-scale wireless sensor networks (WSNs). Even though the ICN approach can significantly reduce the networ...Show More
*** Information-centric networking (ICN) has played an increasingly important role in the next generation network design. However, to make better use of request-response communication mode in the ICN network, revoke user privileges more efficiently and protect user privacy more safely, an effective access control mechanism is needed. In this paper, we propose IBSS (identi...Show More
*** Social networks are very important social cyberspaces for people. Currently, information-centric networks (ICN) are the main trend of next-generation networks, which promote traditional social networks to information-centric social networks (IC-SN). Because of the complexity and openness of social networks, the filtering of security servi...Show More
